name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake GIF
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
          
      - name: Push to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
